/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pl.app;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;
import pl.app.jpa.dao.SystemConfigurationDAO;
import pl.app.jpa.dao.UserAccountDAO;
import pl.app.jpa.model.SystemConfiguration;
import pl.app.jpa.model.UserAccount;
import pl.app.jpa.util.HibernateUtil;


import java.io.IOException;
import java.util.Date;

public class App extends Application {

    public static void main(String[] args) {

        HibernateUtil.getSession();

        HibernateUtil.closeSession();
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws IOException {
        Parent root = FXMLLoader.load(getClass().getResource("/fxml/main.fxml"));
        primaryStage.setTitle("Hello World");
        primaryStage.setScene(new Scene(root, 800, 800));
        primaryStage.show();
    }
}
