/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pl.app;

public class App {
    String greeting = "maslo";

    public static void main(String[] args) {
        System.out.println("chuj XD DDDDDDD");
    }

    public String getGreeting(){
        return greeting;
    }
}
