/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pl.app.main;

import javafx.application.Application;
import javafx.scene.Group;
import javafx.scene.Node;
import javafx.scene.Scene;
import javafx.stage.Stage;
import pl.app.screenManager.ScreenController;
import pl.app.screenManager.ScreenLoader;
import pl.app.screenManager.ScreenSetter;
import pl.app.screenManager.ScreensProperty;


public class LaunchApp extends Application {

    private static Stage primaryStage;

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) {

        setPrimaryStage(primaryStage);


        ScreenController screenController = new ScreenController();

        //załadowanie fxml
        ScreenLoader screenLoader = new ScreenLoader(screenController, ScreensProperty.HOME_SCREEN.getScreenPath());
        Node preparedScreen = screenLoader.loadScreen();

        //wyświetlenie fxml
        ScreenSetter screenSetter = new ScreenSetter(screenController, preparedScreen);
        screenSetter.homeScreen();


        Group root = new Group();
        root.getChildren().addAll(screenController);
        Scene scene = new Scene(root);
        primaryStage.setScene(scene);
        primaryStage.show();

        primaryStage.setResizable(false);

        primaryStage.setOnCloseRequest(e ->
        {
            e.consume();

            primaryStage.close();
        });
    }

    public static Stage getPrimaryStage() {
        return primaryStage;
    }

    private static void setPrimaryStage(Stage primaryStage) {
        LaunchApp.primaryStage = primaryStage;
    }


}
