/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pl.app;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;
import pl.app.jpa.dao.UserAccountDAO;
import pl.app.jpa.model.UserAccount;


import java.io.IOException;

public class LaunchApp extends Application {

    public static void main(String[] args) {


        UserAccount userAccount1 = new UserAccount("test", "test", "test", "test", 12345678908L, "dsada@example.com", "+48000000000");
        UserAccount userAccount2 = new UserAccount("test", "test", "test", "test", 12345678902L, "dsada@example.com", "+48000000000");

        UserAccountDAO userAccountDAO = new UserAccountDAO();


        userAccountDAO.addObject(userAccount1);
        userAccountDAO.addObject(userAccount2);

        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws IOException {
        Parent root = FXMLLoader.load(getClass().getResource("/fxml/main.fxml"));
        primaryStage.setTitle("Hello World");
        primaryStage.setScene(new Scene(root, 800, 800));
        primaryStage.show();
    }
}
